#!/usr/bin/with-contenv bash

PUID="${PUID:-1000}"
PGID="${PGID:-1000}"

groupmod -o -g "$PGID" jessenich
usermod -o -u "$PUID" jessenich

cat <<EOF
To support LSIO projects visit:
https://www.linuxserver.io/donate/

-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
EOF

time32="$(date +%Y)"

if [[ "$time32" == "1970" || "$time32" == "1969" ]] && [ "$(uname -m)" == "armv7l" ]; then
  cat <<'EOF'
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Apps will not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
EOF

  sleep infinity
fi

chown jessenich:jessenich /app
chown jessenich:jessenich /config
chown jessenich:jessenich /defaults
