name: "Push Docker Image"

on:
  push:
    tags:
      - "v*"

env:
  TARGET_PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7

  GHCR_URL: ghcr.io
  GHCR_LIBRARY: jessenich
  GHCR_REPO: alpine
  DOCKERHUB_LIBRARY: jessenich91
  DOCKERHUB_REPO: alpine
  LABELS: |
    maintainer=Jesse N. <jesse@keplerdev.com>
    org.opencontainers.image.source=https://github.com/jessenich/docker-alpine/

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release-name: [ 'focal' ]
        arch: [ '', '.aarch64', ]
      fail-fast: false

    name: "Build Ubuntu - Release: ${{ matrix.release-name }} | Arch: ${{ matrix.arch }}"
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
            version: latest
            install: true
            driver-opts: image=moby/buildkit:master
            use: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        env:
          release-name: "${{ matrix.release-name }}"
        with:
          github-token:  ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.LABELS }}
          images: |
            "docker.io/${{ env.DOCKERHUB_LIBRARY }}/${{ env.DOCKERHUB_REPO }}"
            "ghcr.io/${{ env.GHCR_LIBRARY }}/${{ env.GHCR_REPO }}"
          tags: |
            type=raw,enable=true,priority=100,value=latest
            type=semver,enable=true,priority=200,pattern={{major}}.{{minor}}.{{patch}}

      - name: Build & Push Latest
        uses: docker/build-push-action@v2
        env:
          platforms: "${{ env.TARGET_PLATFORMS }}"
        with:
          context: .
          file: ./Dockerfile${{ matrix.arch }}
          labels: ${{ steps.meta.output.labels }}
          target: ${{ matrix.target }}
          build-args: |
            REL=${{ matrix.release-name }}
            ARCH=${{ matrix.arch }}
            OVERLAY_ARCH=${{ matrix.arch }}
            TZ=America/New_York
          platforms: ${{ env.platforms }}
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
